export const courses = [
  {
    id: 1,
    title: "Departmento Operanciones",
    image: "./images/course1.jpg",
    rating: 2,
    repeated: 32,
    date: "2021-08-01",
  },
  {
    id: 2,
    title: "Roglamento Corporativo",
    image: "./images/course2.jpg",
    rating: 5,
    repeated: 12,
    date: "2021-08-01",
  },
  {
    id: 3,
    title: "Communication y Servico al Cliente",
    image: "./images/course3.jpg",
    rating: 3,
    repeated: 6,
    date: "2021-08-01",
  },
  {
    id: 4,
    title: "Departmento Operanciones",
    image: "./images/course2.jpg",
    rating: 1,
    repeated: 2,
    date: "2021-08-01",
  },
  {
    id: 5,
    title: "Departmento Operanciones",
    image: "./images/course3.jpg",
    rating: 1,
    repeated: 10,
    date: "2021-08-01",
  },
  {
    id: 6,
    title: "Departmento Operanciones",
    image: "./images/course3.jpg",
    rating: 4,
    repeated: 5,
    date: "2021-08-01",
  },
  {
    id: 7,
    title: "Departmento Operanciones",
    image: "./images/course3.jpg",
    rating: 5,
    repeated: 16,
    date: "2021-08-01",
  },
];
export const sections = [1, 2, 3, 4, 5, 6];
